apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo-app-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo-app
  template:
    metadata:
      labels:
        app: cicd-demo-app
    spec:
      containers:
      - name: cicd-demo-app-container
        image: lemonday/viettelci-cd
        ports:
        - containerPort: 3000
        readinessProbe: # Kiểm tra xem container đã sẵn sàng nhận request chưa
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe: # Kiểm tra xem container còn "sống" không
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
